import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  modalContent: {
    width: Math.min(width, 430), // Máximo 430 para tablets
    minHeight: height * 0.6,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    borderRadius: 20,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderLeftWidth: 5,           // <<--- BORDE IZQUIERDO COLOR
    borderLeftColor: "#D35400",
  },
  detailImage: {
    width: Math.min(width * 0.66, 220),
    height: Math.min(width * 0.66, 220),
    borderRadius: 16,
    marginTop: 16,
    marginBottom: 20,
    backgroundColor: "#e9e9e9",
    borderWidth: 1.5,
    borderColor: "hsl(197, 93%, 29%)",
    alignSelf: "center",
    resizeMode: "cover",
  },
  detailTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#232323",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  detailDesc: {
    fontSize: 17,
    color: "#444",
    marginBottom: 20,
    textAlign: "justify",
    lineHeight: 24,
    paddingHorizontal: 6,
  },
  socialRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 8,
  },
  socialIcon: {
    width: 44,
    height: 44,
    marginHorizontal: 9,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e3e9f0",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 1, height: 2 },
    elevation: 2,
  },
  socialBox: {
    width: "92%",
    backgroundColor: "#f4f8ff",
    borderRadius: 14,
    padding: 16,
    marginVertical: 28,
    alignItems: "center",
    borderBottomWidth: 4,
    borderBottomColor: "#3b5998",
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  socialTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#3b5998",
    marginBottom: 12,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)", // Puedes ajustar el 0.45 para más/menos transparencia
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000, // asegurarte de que esté arriba de todo
  },
  closeButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 20,
    backgroundColor: "#fff",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 4,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 2 },
  },
  closeText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#232323",
    lineHeight: 26,
  },
});
